swagger: '2.0'
info:
  version: 1.0.0
  title: Star Wars API 
host: localhost:8000
basePath: /api
schemes:
  - http
paths:
  /characters:
    get:
      tags:
        - characters
      operationId: get_characters
      description:  Retrieve the list of characters
      responses:
        200:
          description: List of characters
          schema:
            type: array
            items:
                $ref: "#/definitions/Character"
    post:
      tags:
        - characters
      description: Create a new character
      operationId: add_character
      parameters:
        - in: body
          name: character
          description: Character object to be added
          required: true
          schema:
            $ref: '#/definitions/Character'
      responses:
        200:
          description: Character added 
          schema:
            $ref: '#/definitions/Character'
        400:
          description: TODO
  /characters/{character_id}:
    get:
      tags:
        - characters
      summary: Find a character by id
      description: Returns a single character
      operationId: get_character_by_id
      parameters:
        - name: character_id
          in: path
          description: ID of character to return
          required: true
          type: integer
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Character'
        400:
          description: Invalid ID supplied
        404:
          description: Character not found
    put:
      tags:
        - characters
      summary: Update an existing character
      operationId: update_character
      parameters:
        - in: path
          name: character_id
          description: Character id to delete
          required: true
          type: integer
        - in: body
          name: character
          description: Character object to be edited
          required: true
          schema:
            $ref: '#/definitions/Character'
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Character not found
        405:
          description: Validation exception
    delete:
      tags:
        - other_tag
      summary: Deletes a Character
      description: ''
      operationId: delete_character
      parameters:
        - in: path
          name: character_id
          description: Character id to delete
          required: true
          type: integer
      responses:
        200:
          description: Deleted
        400:
          description: Invalid ID supplied
        404:
          description: Character not found
definitions:
  Character:
    type: object
    required:
      - name
      - species
    properties:
      id:
        type: integer
      name:
        type: string
      species:
        type: string
        description: Species of the character
        enum:
          - Human
          - Robot
          - Wookie 
          - Ewok
          - "Yoda's species"
        default: Human
      photos:
        type: array
        items:
          $ref: '#/definitions/Photo'
      born_planet:
        $ref: '#/definitions/Planet'
  Planet:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      diameter:
        type: integer
      climate:
        type: string
      population: 
        type: integer
  Photo:
    type: object
    properties:
      name:
        type: string
      url:
        type: string